### ISSUE TITLE
No automatic pasting

### ISSUE THREAD

**Issue by tomcek42** [Carson-Shook/Winclipper#5]
Is there a way that the automatic pasting can be disabled? For me it is sometimes very disturbing that this happens.

Thank you!

**Comment by Carson-Shook** [comment]
Hmmm, I’m not quite sure what you mean. Winclipper should only attempt to paste when clicking on a value from the menu. If that is the behavior you’re referring to, I think I could add a toggle for that.

In cases where it was turned off, clicking an item in the Winclipper menu would only add the selected value to the clipboard, but not simulate the Ctrl+V press. Would that resolve this issue?

**Comment by tomcek42** [comment]
Hey Carson, this is exaclty what I mean. I would be perfect. The reason for me to turn automatic pasting off is that I work most of the time on remote site and switch very fast between different sites. The automatich pasting leads often to pasting on the wrong site.

Thank you so much!

**Comment by Carson-Shook** [comment]
Alrighty! Thank you for alerting me to this use-case. I’m in the middle of a restructure to make it easier for me to add additional options in the future, and I think I can definitely slip this in as a feature as soon as I’m done with that.

**Comment by tomcek42** [comment]
This would be so wonderful! Thank you :)

**Comment by Carson-Shook** [comment]
Winclipper 1.4 includes this feature, thank you for the recommendation!
