### ISSUE TITLE
Winclipper crash

### ISSUE THREAD

**Issue by tomcek42** [Carson-Shook/Winclipper#6]
Hello Carson,

it has happened twice now that Winclipper has crashed when I have accessed it. It is not too dramatic, because Winclipper starts quickly and the entries are still available. But it would be nicer without crashes.

Maybe the event-log entry (it's in german) can help you:

Name der fehlerhaften Anwendung: Winclipper.exe, Version: 1.3.4.0, Zeitstempel: 0x5d89a573
Name des fehlerhaften Moduls: d2d1.dll, Version: 10.0.19041.546, Zeitstempel: 0xdf04746a
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000122116
ID des fehlerhaften Prozesses: 0x4dc8
Startzeit der fehlerhaften Anwendung: 0x01d76c2e49800f5d
Pfad der fehlerhaften Anwendung: C:\Program Files\Winclipper\Winclipper.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\SYSTEM32\d2d1.dll
Berichtskennung: f0c12088-0013-452b-bfec-6251cf908340
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

Best regards, Tom

**Comment by Carson-Shook** [comment]
I have deployed an update which will hopefully address many of the crashing issues (unfortunately they have been hard to reproduce so I can't make any guarantees). I'm closing this bug for now, but please open a new one if you experience another crash.
