### ISSUE TITLE
paste immediately just paste a V

### ISSUE THREAD

**Issue by micjoh** [Carson-Shook/Winclipper#7]
Love this program :-) but found a bug

I have paste immediately on
short cut ctrl-shift-v

sometimes when I paste it just pastes a 'v'
If I immediately press ctrl-v it pastes the correct post so it puts the correct data on the clipboard

**Comment by Carson-Shook** [comment]
Hi micjoh!

I'm glad you like my little application ^_^

As for the issue, does it happen with specific programs? I have noticed it occurs in Firefox if I try summoning the menu immediately after opening a new tab. I haven't yet been able to pin down why unfortunately, so if you have any other applications that it occurs in, please list them here.

Thanks!

**Comment by micjoh** [comment]
Hi Carson

I noticed there were some problems so I did a text in word.
I randomly pasted several clips and once in a while it was pasting ’v’. 
It was reproducable in that it happened once in a while but not consistently.
It was not that a certain clip triggered it unfortunately 

I will try to investigate more 

On another note what needs to be installed if I were to try to build this?
Which dependencies are required?

/michael

----- Original message -----

**Comment by Carson-Shook** [comment]
As of release 1.4.2, this issue should be resolved, so I am marking as closed. Thank you so much for your help!

Also you need the C++14 tools for visual studio 2017 to build Winclipper. Additionally, if you would like to use the build system, it uses WiX as well as my own StupidSimpleUpdater project.

**Comment by micjoh** [comment]
Works flawless. Thanks :-)
